# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="${loader_version_range}" #mandatory

# The license for the mod
license="${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/yourusername/mcoptimizer/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="triutilizer" #mandatory

# The version number of the mod
version="1.0.0" #mandatory

# A display name for the mod
displayName="Tri Utilizer" #mandatory

# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

# A text field displayed in the mod UI
authors="Your name here" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
A server-side Minecraft mod that enhances CPU utilization through efficient parallel processing infrastructure.
Features:
- Configurable work-stealing thread pool for parallel task execution
- Smart thread management based on system capabilities
- Designed for server performance without memory optimization
- Full compatibility with Valkyrien Skies and other mods
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.triutilizer]] #mandatory
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.triutilizer]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.triutilizer]]
    modId="ferritecore"
    mandatory=true
    versionRange="[5.0.0,)" # FerriteCore version for 1.20.1
    ordering="NONE"
    side="BOTH"
[[dependencies.mcoptimizer]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="${forge_version_range}" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="SERVER"

[[dependencies.mcoptimizer]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="SERVER"
